[package]
name = "tongs-server"
version = "0.0.0"
authors = ["Shoyu Vanilla <modulo641@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
actix-web = "4.0.1"
actix-web-lab = "0.16.0"
